// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSalonLjepote.Service.Database;

#nullable disable

namespace eSalonLjepote.Service.Migrations
{
    [DbContext(typeof(ESalonLjepoteContext))]
    [Migration("20251129112305_initialDB")]
    partial class initialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eSalonLjepote.Service.Database.Administrator", b =>
                {
                    b.Property<int>("AdministratorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdministratorId"));

                    b.Property<DateTime?>("DatumZaposlenja")
                        .HasColumnType("datetime");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("OpisPosla")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AdministratorId")
                        .HasName("PK__Administ__ACDEFED39E30171F");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Administrator", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Galerija", b =>
                {
                    b.Property<int>("GalerijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GalerijaId"));

                    b.Property<int>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("GalerijaId")
                        .HasName("PK__Galerija__39DCA3DB934C538C");

                    b.HasIndex("AdministratorId");

                    b.ToTable("Galerija", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Klijenti", b =>
                {
                    b.Property<int>("KlijentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlijentId"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("NarudzbaId")
                        .HasColumnType("int");

                    b.Property<int?>("UslugaId")
                        .HasColumnType("int");

                    b.HasKey("KlijentId")
                        .HasName("PK__Klijenti__5F05D8AE56D1252D");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("NarudzbaId");

                    b.HasIndex("UslugaId");

                    b.ToTable("Klijenti", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<DateTime?>("DatumRodjenja")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Spol")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KorisnikId")
                        .HasName("PK__Korisnik__80B06D41211C7C55");

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.KorisnikUloga", b =>
                {
                    b.Property<int>("KorisnikUlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikUlogaId"));

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikUlogaId")
                        .HasName("PK__Korisnik__1608726E523E7C40");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisnikUloga", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Korpa", b =>
                {
                    b.Property<int>("KorpaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorpaId"));

                    b.Property<decimal?>("Cijena")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Kolicina")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("ProizvodId")
                        .HasColumnType("int");

                    b.HasKey("KorpaId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ProizvodId");

                    b.ToTable("Korpa", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Narudzba", b =>
                {
                    b.Property<int>("NarudzbaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NarudzbaId"));

                    b.Property<DateTime?>("DatumNarudzbe")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("IznosNarudzbe")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("KolicinaProizvoda")
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlacanjeId")
                        .HasColumnType("int");

                    b.Property<int?>("ProizvodId")
                        .HasColumnType("int");

                    b.HasKey("NarudzbaId")
                        .HasName("PK__Narudzba__FBEC1377EFA0DB96");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("PlacanjeId");

                    b.HasIndex("ProizvodId");

                    b.ToTable("Narudzba", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.NarudzbaStavka", b =>
                {
                    b.Property<int>("NarudzbaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NarudzbaStavkaId"));

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("NarudzbaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ProizvodId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("NarudzbaStavkaId");

                    b.HasIndex("NarudzbaId");

                    b.HasIndex("ProizvodId");

                    b.ToTable("NarudzbaStavkas");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Novosti", b =>
                {
                    b.Property<int>("NovostiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NovostiId"));

                    b.Property<int?>("Aktivna")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumObjave")
                        .HasColumnType("datetime");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OpisNovisti")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NovostiId")
                        .HasName("PK__Novosti__451A108B7338A4FF");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Novosti", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.OcjeneProizvoda", b =>
                {
                    b.Property<int>("OcjeneProizvodaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OcjeneProizvodaId"));

                    b.Property<int?>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Ocjena")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProizvodId")
                        .HasColumnType("int");

                    b.HasKey("OcjeneProizvodaId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ProizvodId");

                    b.ToTable("OcjeneProizvoda", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Placanje", b =>
                {
                    b.Property<int>("PlacanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlacanjeId"));

                    b.Property<string>("NacinPlacanja")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlacanjeId")
                        .HasName("PK__Placanje__DDE16DECD82236A6");

                    b.ToTable("Placanje", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Proizvod", b =>
                {
                    b.Property<int>("ProizvodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizvodId"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("NazivProizvoda")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ProizvodId")
                        .HasName("PK__Proizvod__21A8BFF863D092F1");

                    b.ToTable("Proizvod", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.RadnoVrijeme", b =>
                {
                    b.Property<int>("RadnoVrijemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RadnoVrijemeId"));

                    b.Property<string>("KolektivniOdmor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NeradniDani")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RadnoVrijemeDo")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RadnoVrijemeOd")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan?>("VrijemePauze")
                        .HasColumnType("time");

                    b.HasKey("RadnoVrijemeId")
                        .HasName("PK__RadnoVri__715793313FEB1A8E");

                    b.ToTable("RadnoVrijeme", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Recenzije", b =>
                {
                    b.Property<int>("RecenzijeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecenzijeId"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("Ocjena")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.Property<string>("OpisRecenzije")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RecenzijeId")
                        .HasName("PK__Recenzij__C077A33644BE8AAA");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Recenzije", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.SalonLjepote", b =>
                {
                    b.Property<int>("SalonLjepoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalonLjepoteId"));

                    b.Property<int>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NazivSalona")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RadnoVrijemeId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SalonLjepoteId")
                        .HasName("PK__SalonLje__E16A2127A1A571C5");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("RadnoVrijemeId");

                    b.ToTable("SalonLjepote", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Termini", b =>
                {
                    b.Property<int>("TerminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerminId"));

                    b.Property<string>("BrojTransakcije")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumTermina")
                        .HasColumnType("datetime");

                    b.Property<int>("KlijentId")
                        .HasColumnType("int");

                    b.Property<int>("UslugaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VrijemeTermina")
                        .HasColumnType("time");

                    b.Property<int>("ZaposleniId")
                        .HasColumnType("int");

                    b.HasKey("TerminId")
                        .HasName("PK__Termini__42126C9559EA80B6");

                    b.HasIndex("KlijentId");

                    b.HasIndex("UslugaId");

                    b.HasIndex("ZaposleniId");

                    b.ToTable("Termini", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Uloga", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaId"));

                    b.Property<string>("NazivUloge")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UlogaId");

                    b.ToTable("Uloga", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Usluga", b =>
                {
                    b.Property<int>("UslugaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UslugaId"));

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("NazivUsluge")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Trajanje")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UslugaId")
                        .HasName("PK__Usluga__0BE5E72F452B3D17");

                    b.ToTable("Usluga", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Zaposleni", b =>
                {
                    b.Property<int>("ZaposleniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZaposleniId"));

                    b.Property<DateTime?>("DatumZaposlenja")
                        .HasColumnType("datetime");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Zanimanje")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ZaposleniId")
                        .HasName("PK__Zaposlen__8D3A91B7793939DB");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Zaposleni", (string)null);
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Administrator", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Administrators")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Korisnik_Administrator");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Galerija", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Administrator", "Administrator")
                        .WithMany("Galerijas")
                        .HasForeignKey("AdministratorId")
                        .IsRequired()
                        .HasConstraintName("FK_Administrator_Galerija");

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Klijenti", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Klijentis")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Korisnik_Klijenti");

                    b.HasOne("eSalonLjepote.Service.Database.Narudzba", null)
                        .WithMany("Klijentis")
                        .HasForeignKey("NarudzbaId");

                    b.HasOne("eSalonLjepote.Service.Database.Usluga", null)
                        .WithMany("Klijentis")
                        .HasForeignKey("UslugaId");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.KorisnikUloga", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Korisnik", "Korisnik")
                        .WithMany("KorisnikUlogas")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Korisnik_KorisniciUloga");

                    b.HasOne("eSalonLjepote.Service.Database.Uloga", "Uloga")
                        .WithMany("KorisnikUlogas")
                        .HasForeignKey("UlogaId")
                        .IsRequired()
                        .HasConstraintName("FK_Uloga_KorisniciUloga");

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Korpa", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Korpas")
                        .HasForeignKey("KorisnikId");

                    b.HasOne("eSalonLjepote.Service.Database.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("ProizvodId");

                    b.Navigation("Korisnik");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Narudzba", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Narudzbas")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK_Korisnik_Narudzba");

                    b.HasOne("eSalonLjepote.Service.Database.Placanje", "Placanje")
                        .WithMany("Narudzbas")
                        .HasForeignKey("PlacanjeId")
                        .HasConstraintName("FK_Placanje_Narudzba");

                    b.HasOne("eSalonLjepote.Service.Database.Proizvod", "Proizvod")
                        .WithMany("Narudzbas")
                        .HasForeignKey("ProizvodId")
                        .HasConstraintName("FK_Proizvod_Narudzba");

                    b.Navigation("Korisnik");

                    b.Navigation("Placanje");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.NarudzbaStavka", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Narudzba", "Narudzba")
                        .WithMany("Stavke")
                        .HasForeignKey("NarudzbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSalonLjepote.Service.Database.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("ProizvodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Narudzba");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Novosti", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Novostis")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Korisnik_Novosti");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.OcjeneProizvoda", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Korisnik", "Korisnik")
                        .WithMany("OcjeneProizvodas")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSalonLjepote.Service.Database.Proizvod", "Proizvod")
                        .WithMany("OcjeneProizvodas")
                        .HasForeignKey("ProizvodId");

                    b.Navigation("Korisnik");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Recenzije", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Recenzijes")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Korisnik_Recenzije");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.SalonLjepote", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Administrator", "Administrator")
                        .WithMany("SalonLjepotes")
                        .HasForeignKey("AdministratorId")
                        .IsRequired()
                        .HasConstraintName("FK_Administrator_SalonLjepote");

                    b.HasOne("eSalonLjepote.Service.Database.RadnoVrijeme", "RadnoVrijeme")
                        .WithMany("SalonLjepotes")
                        .HasForeignKey("RadnoVrijemeId")
                        .IsRequired()
                        .HasConstraintName("FK_RadnoVrijeme_SalonLjepote");

                    b.Navigation("Administrator");

                    b.Navigation("RadnoVrijeme");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Termini", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Klijenti", "Klijent")
                        .WithMany("Terminis")
                        .HasForeignKey("KlijentId")
                        .IsRequired()
                        .HasConstraintName("FK_Klijent_Termini");

                    b.HasOne("eSalonLjepote.Service.Database.Usluga", "Usluga")
                        .WithMany("Terminis")
                        .HasForeignKey("UslugaId")
                        .IsRequired()
                        .HasConstraintName("FK_Usluga_Termini");

                    b.HasOne("eSalonLjepote.Service.Database.Zaposleni", "Zaposleni")
                        .WithMany("Terminis")
                        .HasForeignKey("ZaposleniId")
                        .IsRequired()
                        .HasConstraintName("FK_Zaposleni_Termini");

                    b.Navigation("Klijent");

                    b.Navigation("Usluga");

                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Zaposleni", b =>
                {
                    b.HasOne("eSalonLjepote.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Zaposlenis")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Korisnik_Zaposleni");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Administrator", b =>
                {
                    b.Navigation("Galerijas");

                    b.Navigation("SalonLjepotes");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Klijenti", b =>
                {
                    b.Navigation("Terminis");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Korisnik", b =>
                {
                    b.Navigation("Administrators");

                    b.Navigation("Klijentis");

                    b.Navigation("KorisnikUlogas");

                    b.Navigation("Korpas");

                    b.Navigation("Narudzbas");

                    b.Navigation("Novostis");

                    b.Navigation("OcjeneProizvodas");

                    b.Navigation("Recenzijes");

                    b.Navigation("Zaposlenis");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Narudzba", b =>
                {
                    b.Navigation("Klijentis");

                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Placanje", b =>
                {
                    b.Navigation("Narudzbas");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Proizvod", b =>
                {
                    b.Navigation("Narudzbas");

                    b.Navigation("OcjeneProizvodas");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.RadnoVrijeme", b =>
                {
                    b.Navigation("SalonLjepotes");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Uloga", b =>
                {
                    b.Navigation("KorisnikUlogas");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Usluga", b =>
                {
                    b.Navigation("Klijentis");

                    b.Navigation("Terminis");
                });

            modelBuilder.Entity("eSalonLjepote.Service.Database.Zaposleni", b =>
                {
                    b.Navigation("Terminis");
                });
#pragma warning restore 612, 618
        }
    }
}
